# Generated by Django 5.0.4 on 2024-04-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='person-image')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField(default=0)),
            ],
        ),
    ]
