# Generated by Django 5.0.4 on 2024-04-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='color',
            field=models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('red', 'Red'), ('orange', 'Orange'), ('black', 'Black')], default='green', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='person-image'),
        ),
    ]
